name: Build

on:
  push:
    paths:
      - 'config/glove80.keymap'
  pull_request:
    paths:
      - 'config/glove80.keymap'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/checkout@v3
        with:
          repository: moergo-sc/zmk
          ref: main
          path: src
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-22.05
      - uses: cachix/cachix-action@v12
        with:
          name: moergo-glove80-zmk-dev
          skipPush: true
      - name: Build Glove80 combined firmware
        run: nix-build config -o combined
      - name: Copy result out of nix store
        run: cp combined/glove80.uf2 glove80.uf2
      - name: Configure Git
        run: |
          git config --local user.email "sam.perlmutter227@gmail.com"
          git config --local user.name "Sam Perlmutter"

      - name: Commit file
        run: |
          git add glove80.uf2
          git commit -m "Add generated glove80.uf2 file"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          force: true
